platform :ios, "9.0"
use_frameworks!

target 'Hickery' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

  # Pods for Hickery

  target 'HickeryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HickeryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
