platform :ios, "10.0"
use_frameworks!


target 'Hickery' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking', '~> 3.2.1'
  pod 'FacebookCore', '~> 0.3.1'
  pod 'FacebookLogin', '~> 0.2.0'
  pod 'youtube-ios-player-helper', :git=>'https://github.com/youtube/youtube-ios-player-helper', :commit=>'head'
  pod 'Kingfisher', '~> 4.8.0'
  pod 'Fabric', '~> 1.7.7'
  pod 'Crashlytics', '~> 3.10.2'
  pod 'MobileVLCKit', '~> 3.1.0'
  pod 'PySwiftyRegex', '~> 1.0.0'
  # Pods for Hickery

  target 'HickeryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HickeryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
